### ISSUE TITLE
Adding large folders

### ISSUE THREAD

**Issue by CarnivorousM** [megastruktur/foundryvtt-audio-folder#1]
I am forced to assume this issue is with the way the sounds are brought in through this mod since it works if done individually, I shall try to explain the best I can.

FoundryVTT: 0.6.5
D&D5e: 0.93
Audio Folder: 1.0

I have sorted all my sounds into smaller, easier to handle sound sub-folders (Hoping for 1 playlist per folder). There are a mix of .ogg, .wav, and .mp3 files in these folders. (The files in a given folder is around 50 [combat music] on the high end down to about 5 in others [sounds of things in flight]. There are just shy of 1000 sound files all together across 50 folders)

If I create a Playlist and then select the folder to pull in the sounds - it appears to work on all files. (they all appear and show in the list)

If I attempt to play sounds right away - some of the sounds don't work/won't play.
If I reboot Foundry and then reopen the Playlist - each of the sounds that weren't "working" are gone. (The files that worked right away stay in the list. This seems fairly random and not specific file types. I cleared out a playlist and tried the same folder twice with different results on number of files/which ones it kept)

If I then do an individual sound file load of each of the ones that "didn't work on the bulk upload" - they will function fine and remain through Foundry reboot as expected. (Doing it the regular way - 1 at a time).

The only other audio module am using is Maestro, but if I disable that and attempt - it changes nothing/seems to have no effect on results.

**Comment by megastruktur** [comment]
Hey @CarnivorousM, thanks for reaching me out!

The same issue was reported on Discord yesterday. Can you please specify the OS where the Foundry is running? Is it Windows?
I've tested it on Linux and all works fine. Going to give it a try on Win today and make a fix.
If I won't be able to reproduce the issue with my music files - will you able to share 1 of your small folders with me to test?

**Comment by CarnivorousM** [comment]
Yes, Windows 10. Attached are a small example of sound files from a
smaller folder. They are the only files in that specific folder.
